<?php
require __DIR__ . '/app/bootstrap.php'; require_login(); verify_csrf();
[$scopeSql,$scopeParams]=scope_clause($pdo,'r'); $id=(int)($_GET['id']??0);
$stmt=$pdo->prepare("SELECT r.*,u.name rep,u.email rep_email FROM reports r JOIN users u ON u.id=r.user_id WHERE r.id=? AND $scopeSql"); $stmt->execute(array_merge([$id],$scopeParams)); $r=$stmt->fetch(); if(!$r){ http_response_code(404); exit('Report not found'); }
if($_SERVER['REQUEST_METHOD']==='POST' && is_manager()){
  $status=normalize_status($_POST['status']??'pending'); $comment=trim($_POST['manager_comment']??''); $pdo->prepare('UPDATE reports SET status=?, manager_comment=? WHERE id=?')->execute([$status,$comment,$id]); flash('success','Manager review saved.'); header('Location: report_view.php?id='.$id); exit;
}
render_header('Report Details');
?>
<div class="hero"><div><span class="eyebrow">Report #<?= (int)$r['id'] ?></span><h2><?= e($r['doctor_name']) ?></h2><p><?= e($r['hospital_name']) ?> · <?= e(date('M d, Y g:i A', strtotime($r['visit_datetime']))) ?></p></div><div class="actions"><a class="btn ghost" href="reports.php">Back</a><a class="btn primary" href="report_form.php?id=<?= (int)$r['id'] ?>">Edit</a></div></div>
<div class="report-view"><div class="card"><div class="section-title"><div><span class="eyebrow">Visit Details</span><h2>Report information</h2></div><span class="badge <?= e($r['status']) ?>"><?= e(status_label($r['status'])) ?></span></div><div class="detail-list"><div class="detail"><span>Sales Rep</span><strong><?= e($r['rep']) ?></strong><p class="muted"><?= e($r['rep_email']) ?></p></div><div class="detail"><span>Purpose / Medicine</span><strong><?= e($r['purpose']) ?></strong><p class="muted"><?= e($r['medicine_name']) ?></p></div><div class="detail"><span>Summary</span><p><?= nl2br(e($r['summary'])) ?></p></div><div class="detail"><span>Remarks</span><p><?= nl2br(e($r['remarks'])) ?></p></div><?php if($r['manager_comment']): ?><div class="detail"><span>Manager Comment</span><p><?= nl2br(e($r['manager_comment'])) ?></p></div><?php endif; ?></div></div><div class="grid"><div class="card"><div class="section-title"><div><span class="eyebrow">Contact</span><h2>Doctor profile</h2></div></div><div class="detail-list"><div class="detail"><span>Email</span><?= e($r['doctor_email'] ?: 'Not provided') ?></div><div class="detail"><span>Created</span><?= e(date('M d, Y g:i A', strtotime($r['created_at']))) ?></div><?php if($r['attachment_path']): ?><div class="detail"><span>Attachment</span><a class="btn small" target="_blank" href="<?= e($r['attachment_path']) ?>">Open attachment</a></div><?php endif; ?><?php if($r['signature_path']): ?><div class="detail"><span>Signature</span><a class="btn small" target="_blank" href="<?= e($r['signature_path']) ?>">Open signature</a></div><?php endif; ?></div></div><?php if(is_manager()): ?><form class="card" method="post"><input type="hidden" name="_csrf" value="<?= csrf_token() ?>"><div class="section-title"><div><span class="eyebrow">Review</span><h2>Manager action</h2></div></div><div class="field"><label>Status</label><select name="status"><?php foreach(['pending','approved','needs_changes'] as $s): ?><option value="<?= $s ?>" <?= $r['status']===$s?'selected':'' ?>><?= status_label($s) ?></option><?php endforeach; ?></select></div><br><div class="field"><label>Comment</label><textarea name="manager_comment"><?= e($r['manager_comment']) ?></textarea></div><br><button class="btn primary" style="width:100%">Save Review</button></form><?php endif; ?></div></div>
<?php render_footer(); ?>
